# Generated by Django 3.1.2 on 2020-12-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingTable',
            fields=[
                ('Booking_Id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=100)),
                ('show_date', models.DateField()),
                ('show_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('Movie_Id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Release_date', models.DateField(verbose_name='Release Date')),
            ],
        ),
    ]
